### ISSUE TITLE
Bot is failing to start

### ISSUE THREAD

**Issue by save-lalatina** [JokelBaf/Sanya-Nya#5]
Can't start the bot after deployed to Railway.

**Here is the error:**
```
Traceback (most recent call last):
  File "bot.py", line 9, in <module>
    from Utils.Bot import Logger, Functions
  File "Utils\Bot\Functions.py", line 13, in <module>
    def slash_command_log(ctx: discord.ApplicationContext, command: str) -> None:
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'discord' has no attribute 'ApplicationContext'
```

**Comment by jokelbaf** [comment]
On Railway go to **Bot Project** > **Settings**.

Find **Build command** field and paste the following command there:
```
pip uninstall -y discord.py && pip uninstall -y py-cord && pip install py-cord
```

This erorr occurs cause wavelink added `discord.py` library to the list of it's dependencies and this bot is written for `py-cord`. I'll update deploy instruction in readme. Thanks for your issue.

**Comment by save-lalatina** [comment]
Everything is working now! Thank you!
